runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /js
  static_dir: js

- url: /.*
  script: markdistrictwebsite.app

libraries:
- name: jinja2
  version: latest

# skip_files:
# - /home/ubuntu/workspace/.c9
# - /home/ubuntu/workspace/.git
# - /home/ubuntu/workspace/google-cloud-sdk
# - /home/ubuntu/workspace/README.md
